In [1]:
import numpy as np

In [57]:
# Create a numpy array of size 10, filled with zeros.
np.zeros(10,dtype = np.uint8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [58]:
# Create a numpy array with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [59]:
# Create a numpy matrix of 2*2 integers, filled with ones.
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [61]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [65]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
x = np.arange(2,10)
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [67]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
x1 = np.random.rand(2,2) 
np.zeros_like(x1)

array([[0., 0.],
       [0., 0.]])

In [66]:
# Create a numpy matrix of 4*4 integers, filled with fives.
np.ones((4,4),dtype = int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [69]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
x2 = np.random.rand(3,3) 
np.ones_like(x2,dtype = int)*7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [70]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.
np.random.randint(1,11,size =(1,3))

array([[1, 1, 5]])

In [88]:
# Create a 3*3*3 numpy matrix, filled with random float values.
(10-1)*np.random.random((3,3,3)).round(2)+1

array([[[ 3.34,  2.71,  3.61],
        [ 9.46,  4.87, 10.  ],
        [ 3.43,  1.18,  8.92]],

       [[ 7.39,  9.73,  4.15],
        [ 9.37,  8.74,  6.31],
        [ 6.94,  5.77,  4.24]],

       [[ 7.39,  9.55,  8.29],
        [ 8.29,  7.12,  2.89],
        [ 2.89,  5.32,  5.41]]])

In [92]:
# Given the X python list convert it to an Y numpy array
X3 = [1, 2, 3]
print(type(X3))
Y1 = np.array(X)
print(type(Y1))

<class 'list'>
<class 'numpy.ndarray'>


In [98]:
# Given the X numpy array, make a copy and store it on Y.
X = np.array([5,2,3], dtype=int)
print(id(X))
Y = np.copy(X)
print(id(Y))

2305575113936
2305575263216


In [117]:
# Create a numpy array with numbers from 1 to 10
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
# Create a numpy array with the odd numbers between 1 to 10
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [119]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [146]:
# how the memory size of the given Z numpy matrix
Z1 = np.zeros((10,10),dtype=np.uint8)
print(Z1.nbytes)

100


In [164]:
# Given the X numpy array, show it's first element
x4 = np.arange(1,10)
print(x4[0])
# Given the X numpy array, show it's last element
print(x4[-1])
# Given the X numpy array, show it's first three elements
print(x4[:3])
# Given the X numpy array, show all middle elements
print(x4[1:-1])
# Given the X numpy array, show the elements in reverse position
print(x4[::-1])
# Given the X numpy array, show the elements in an odd position
print(x4[::2])


1
9
[1 2 3]
[2 3 4 5 6 7 8]
[9 8 7 6 5 4 3 2 1]
[1 3 5 7 9]


In [189]:
x5 = np.random.randint(10,size=(4,4))
x5

array([[9, 7, 6, 1],
       [4, 7, 8, 3],
       [1, 3, 7, 7],
       [5, 1, 1, 6]])

In [195]:
# Given the X numpy matrix, show the first row elements
print(x5[0])
# Given the X numpy matrix, show the last row elements
print(x5[-1])
# Given the X numpy matrix, show the first element on first row
print(x5[0,0])
# Given the X numpy matrix, show the last element on last row
print(x5[-1,-1])
# Given the X numpy matrix, show the middle row elements
print(x5[1:-1])
# Given the X numpy matrix, show the first two elements on the first two rows
print(x5[:2,:2])
# Given the X numpy matrix, show the last two elements on the last two rows
print(x5[-2:,-2:])

[9 7 6 1]
[5 1 1 6]
9
6
[[4 7 8 3]
 [1 3 7 7]]
[[9 7]
 [4 7]]
[[7 7]
 [1 6]]


In [216]:
# Convert the given integer numpy array to float
x6= np.arange(1,10,dtype = np.uint8)
print(x6.astype(float))
# Reverse the given numpy array (first element becomes last)
print(x6[::-1])

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[9 8 7 6 5 4 3 2 1]


In [234]:
# Order (sort) the given numpy array
x7 = np.array([0, 10, -5, 40, -3])
np.sort(x7)
# Given the X numpy array, set the fifth element equal to 1
x7[4] = 1
print(x7)
# Given the X numpy array, change the 50 with a 40
x8 = np.array([10, 20, 30, 50])
for i in range(len(x8)):
    if x8[i] == 50:
        x8[i] = 40
    else:
        continue
print(x8)

[ 0 10 -5 40  1]
[10 20 30 40]


In [241]:
# Given the X numpy matrix, change the last row with all 1
x9 = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
x9[-1] = np.ones_like(x9[-1])
print(x9)
# Given the X numpy matrix, change the last item on the last row with a 0
x9[-1,-1] = 0
print(x9)
# Given the X numpy matrix, add 5 to every element
x9 +=5
print(x9)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  0]]
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [ 6  6  6  5]]


In [265]:
# Given the X numpy array, make a mask showing negative elements
x10 = np.array([-1,2,0,-4,5,6,0,0,-9,10])
print(x10 <0)
# Given the X numpy array, get the negative elements
for i in x10:
    if i < 0:
        print(i)
mask10 = x10<0
print(x10[mask10 == True])
# Given the X numpy array, get numbers higher than 5
x11 = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask11 = x11>5
print(x11[mask11])
# Given the X numpy array, get numbers higher than the elements mean
x12 = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask12 = x12>x12.mean()
print(x12[mask12])
# Given the X numpy array, get numbers equal to 2 or 10
x13 = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
x13[(x13==2)|(x13==10)]


[ True False False  True False False False False  True False]
-1
-4
-9
[-1 -4 -9]
[ 6 10]
[ 2  5  6 10]


array([ 2, 10])

In [274]:
# Given the X numpy array, return True if none of its elements is zero
x14 = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
print(x14.all())
# Given the X numpy array, return True if any of its elements is zero
print(np.any(x14==0))

False
True


In [279]:
# Given the X numpy array, show the sum of its elements
print(x14.sum())
# Given the X numpy array, show the mean value of its elements
print(x14.mean())
# Given the X numpy matrix, show the sum of its columns
x15 =  np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])
print(x15.sum(axis = 0))
# Given the X numpy matrix, show the mean value of its rows
print(x15.mean(axis=1))
# Given the X numpy array, show the max value of its elements
x14.max()

9
0.9
[28 32 36 40]
[ 2.5  6.5 10.5 14.5]


10

In [280]:
# np.info("all")

In [281]:
# np.lookfor("element 0")